# -*- coding: utf-8 -*-
"""
Created on Tue Feb 23 16:12:25 2021

AeroDrop_dispersed_analysis.py:
    loads and analyzes compiled data generated by AeroDrop_dispersed.py

@author: Samuel Albert
"""


import numpy as np


# =============================================================================
# Load data
# =============================================================================
filename = '../results/DUMMY_AeroDrop_dispersed_6_0223161022.npz'
data = np.load(filename, allow_pickle = True)

xxvecArr_O = data['xxvecArr_O']
tvecArr_O = data['tvecArr_O']
sigdvecArr_O = data['sigdvecArr_O']
tsvecArr_O = data['tsvecArr_O']
BCList_O = data['BCList_O']
L_DList_O = data['L_DList_O']
gam0List = data['gam0List']
v0List = data['v0List']
raErrList_O = data['raErrList_O']
DVList_O = data['DVList_O']
tsfList_O = data['tsfList_O']
sigdfList_O = data['sigdfList_O']
rafList_O = data['rafList_O']
rpfList_O = data['rpfList_O']
engfList_O = data['engfList_O']
xxvecArr_P = data['xxvecArr_P']
tvecArr_P = data['tvecArr_P']
sigvecArr = data['sigvecArr']
sig0ListArr = data['sig0ListArr']
sfErrList_P = data['sfErrList_P']
hfErrList_P = data['hfErrList_P']
vfErrList_P = data['vfErrList_P']
xxvecArr_PBC = data['xxvecArr_PBC']
tvecArr_PBC = data['tvecArr_PBC']
sfErrList_PBC = data['sfErrList_PBC']
hfErrList_PBC = data['hfErrList_PBC']
vfErrList_PBC = data['vfErrList_PBC']

del data

























