# -*- coding: utf-8 -*-
"""
Created on Tue Feb 23 15:28:35 2021

AeroDrop_dispersed_compile.py:
    compiles multiple data files generated by AeroDrop_dispersed into one

@author: Samuel Albert
"""


import numpy as np

